USE music_platform;
ALTER TABLE t_admin MODIFY COLUMN status SMALLINT DEFAULT 1;
ALTER TABLE t_user MODIFY COLUMN status SMALLINT DEFAULT 1;
ALTER TABLE t_user MODIFY COLUMN gender SMALLINT DEFAULT 0;

