// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_album")
public class Album {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "album_id")
    private String albumId;
    @Column(name = "name")
    private String name;
    @Column(name = "cover")
    private String cover;
    @Column(name = "artist_id")
    private Long artistId;
    @Column(name = "publish_date")
    private LocalDate publishDate;
    @Column(name = "description")
    private String description;
    @Column(name = "song_count")
    private Integer songCount;
    @Column(name = "status")
    private Integer status;
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getAlbumId() {
        return this.albumId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public Long getArtistId() {
        return this.artistId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getPublishDate() {
        return this.publishDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbumId(final String albumId) {
        this.albumId = albumId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtistId(final Long artistId) {
        this.artistId = artistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPublishDate(final LocalDate publishDate) {
        this.publishDate = publishDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Album)) return false;
        final Album other = (Album) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$artistId = this.getArtistId();
        final java.lang.Object other$artistId = other.getArtistId();
        if (this$artistId == null ? other$artistId != null : !this$artistId.equals(other$artistId)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$albumId = this.getAlbumId();
        final java.lang.Object other$albumId = other.getAlbumId();
        if (this$albumId == null ? other$albumId != null : !this$albumId.equals(other$albumId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        final java.lang.Object this$publishDate = this.getPublishDate();
        final java.lang.Object other$publishDate = other.getPublishDate();
        if (this$publishDate == null ? other$publishDate != null : !this$publishDate.equals(other$publishDate)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Album;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $artistId = this.getArtistId();
        result = result * PRIME + ($artistId == null ? 43 : $artistId.hashCode());
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $albumId = this.getAlbumId();
        result = result * PRIME + ($albumId == null ? 43 : $albumId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        final java.lang.Object $publishDate = this.getPublishDate();
        result = result * PRIME + ($publishDate == null ? 43 : $publishDate.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Album(id=" + this.getId() + ", albumId=" + this.getAlbumId() + ", name=" + this.getName() + ", cover=" + this.getCover() + ", artistId=" + this.getArtistId() + ", publishDate=" + this.getPublishDate() + ", description=" + this.getDescription() + ", songCount=" + this.getSongCount() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Album() {
    }

    @java.lang.SuppressWarnings("all")
    public Album(final Long id, final String albumId, final String name, final String cover, final Long artistId, final LocalDate publishDate, final String description, final Integer songCount, final Integer status, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.albumId = albumId;
        this.name = name;
        this.cover = cover;
        this.artistId = artistId;
        this.publishDate = publishDate;
        this.description = description;
        this.songCount = songCount;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
