// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_artist")
public class Artist {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "artist_id")
    private String artistId;
    @Column(name = "name")
    private String name;
    @Column(name = "avatar")
    private String avatar;
    @Column(name = "description")
    private String description;
    @Column(name = "song_count")
    private Integer songCount;
    @Column(name = "album_count")
    private Integer albumCount;
    @Column(name = "tags")
    private String tags;
    @Column(name = "status")
    private Integer status;
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getArtistId() {
        return this.artistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getAlbumCount() {
        return this.albumCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtistId(final String artistId) {
        this.artistId = artistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbumCount(final Integer albumCount) {
        this.albumCount = albumCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setTags(final String tags) {
        this.tags = tags;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Artist)) return false;
        final Artist other = (Artist) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$albumCount = this.getAlbumCount();
        final java.lang.Object other$albumCount = other.getAlbumCount();
        if (this$albumCount == null ? other$albumCount != null : !this$albumCount.equals(other$albumCount)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$artistId = this.getArtistId();
        final java.lang.Object other$artistId = other.getArtistId();
        if (this$artistId == null ? other$artistId != null : !this$artistId.equals(other$artistId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$avatar = this.getAvatar();
        final java.lang.Object other$avatar = other.getAvatar();
        if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Artist;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $albumCount = this.getAlbumCount();
        result = result * PRIME + ($albumCount == null ? 43 : $albumCount.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $artistId = this.getArtistId();
        result = result * PRIME + ($artistId == null ? 43 : $artistId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $avatar = this.getAvatar();
        result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Artist(id=" + this.getId() + ", artistId=" + this.getArtistId() + ", name=" + this.getName() + ", avatar=" + this.getAvatar() + ", description=" + this.getDescription() + ", songCount=" + this.getSongCount() + ", albumCount=" + this.getAlbumCount() + ", tags=" + this.getTags() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Artist() {
    }

    @java.lang.SuppressWarnings("all")
    public Artist(final Long id, final String artistId, final String name, final String avatar, final String description, final Integer songCount, final Integer albumCount, final String tags, final Integer status, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.artistId = artistId;
        this.name = name;
        this.avatar = avatar;
        this.description = description;
        this.songCount = songCount;
        this.albumCount = albumCount;
        this.tags = tags;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
