// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_notification")
public class Notification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "uid")
    private String uid;
    @Column(name = "type")
    private String type;
    @Column(name = "title")
    private String title;
    @Column(name = "content")
    private String content;
    @Column(name = "link")
    private String link;
    @Column(name = "is_read")
    private Integer isRead;
    @Column(name = "read_at")
    private LocalDateTime readAt;
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUid() {
        return this.uid;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public String getLink() {
        return this.link;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getReadAt() {
        return this.readAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUid(final String uid) {
        this.uid = uid;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setLink(final String link) {
        this.link = link;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsRead(final Integer isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    public void setReadAt(final LocalDateTime readAt) {
        this.readAt = readAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Notification)) return false;
        final Notification other = (Notification) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$isRead = this.getIsRead();
        final java.lang.Object other$isRead = other.getIsRead();
        if (this$isRead == null ? other$isRead != null : !this$isRead.equals(other$isRead)) return false;
        final java.lang.Object this$uid = this.getUid();
        final java.lang.Object other$uid = other.getUid();
        if (this$uid == null ? other$uid != null : !this$uid.equals(other$uid)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$link = this.getLink();
        final java.lang.Object other$link = other.getLink();
        if (this$link == null ? other$link != null : !this$link.equals(other$link)) return false;
        final java.lang.Object this$readAt = this.getReadAt();
        final java.lang.Object other$readAt = other.getReadAt();
        if (this$readAt == null ? other$readAt != null : !this$readAt.equals(other$readAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Notification;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $isRead = this.getIsRead();
        result = result * PRIME + ($isRead == null ? 43 : $isRead.hashCode());
        final java.lang.Object $uid = this.getUid();
        result = result * PRIME + ($uid == null ? 43 : $uid.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $link = this.getLink();
        result = result * PRIME + ($link == null ? 43 : $link.hashCode());
        final java.lang.Object $readAt = this.getReadAt();
        result = result * PRIME + ($readAt == null ? 43 : $readAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Notification(id=" + this.getId() + ", uid=" + this.getUid() + ", type=" + this.getType() + ", title=" + this.getTitle() + ", content=" + this.getContent() + ", link=" + this.getLink() + ", isRead=" + this.getIsRead() + ", readAt=" + this.getReadAt() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Notification() {
    }

    @java.lang.SuppressWarnings("all")
    public Notification(final Long id, final String uid, final String type, final String title, final String content, final String link, final Integer isRead, final LocalDateTime readAt, final LocalDateTime createdAt) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.title = title;
        this.content = content;
        this.link = link;
        this.isRead = isRead;
        this.readAt = readAt;
        this.createdAt = createdAt;
    }
}
