// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_playlist")
public class Playlist {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "playlist_id")
    private String playlistId;
    @Column(name = "name")
    private String name;
    @Column(name = "cover")
    private String cover;
    @Column(name = "description")
    private String description;
    @Column(name = "creator_uid")
    private String creatorUid;
    @Column(name = "song_count")
    private Integer songCount;
    @Column(name = "play_count")
    private Long playCount;
    @Column(name = "collect_count")
    private Integer collectCount;
    @Column(name = "tags")
    private String tags;
    @Column(name = "is_official")
    private Integer isOfficial;
    @Column(name = "status")
    private Integer status;
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getCreatorUid() {
        return this.creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCollectCount() {
        return this.collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsOfficial() {
        return this.isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getDeletedAt() {
        return this.deletedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final String playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatorUid(final String creatorUid) {
        this.creatorUid = creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectCount(final Integer collectCount) {
        this.collectCount = collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setTags(final String tags) {
        this.tags = tags;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsOfficial(final Integer isOfficial) {
        this.isOfficial = isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeletedAt(final LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Playlist)) return false;
        final Playlist other = (Playlist) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$collectCount = this.getCollectCount();
        final java.lang.Object other$collectCount = other.getCollectCount();
        if (this$collectCount == null ? other$collectCount != null : !this$collectCount.equals(other$collectCount)) return false;
        final java.lang.Object this$isOfficial = this.getIsOfficial();
        final java.lang.Object other$isOfficial = other.getIsOfficial();
        if (this$isOfficial == null ? other$isOfficial != null : !this$isOfficial.equals(other$isOfficial)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$creatorUid = this.getCreatorUid();
        final java.lang.Object other$creatorUid = other.getCreatorUid();
        if (this$creatorUid == null ? other$creatorUid != null : !this$creatorUid.equals(other$creatorUid)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$deletedAt = this.getDeletedAt();
        final java.lang.Object other$deletedAt = other.getDeletedAt();
        if (this$deletedAt == null ? other$deletedAt != null : !this$deletedAt.equals(other$deletedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Playlist;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $collectCount = this.getCollectCount();
        result = result * PRIME + ($collectCount == null ? 43 : $collectCount.hashCode());
        final java.lang.Object $isOfficial = this.getIsOfficial();
        result = result * PRIME + ($isOfficial == null ? 43 : $isOfficial.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $creatorUid = this.getCreatorUid();
        result = result * PRIME + ($creatorUid == null ? 43 : $creatorUid.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $deletedAt = this.getDeletedAt();
        result = result * PRIME + ($deletedAt == null ? 43 : $deletedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Playlist(id=" + this.getId() + ", playlistId=" + this.getPlaylistId() + ", name=" + this.getName() + ", cover=" + this.getCover() + ", description=" + this.getDescription() + ", creatorUid=" + this.getCreatorUid() + ", songCount=" + this.getSongCount() + ", playCount=" + this.getPlayCount() + ", collectCount=" + this.getCollectCount() + ", tags=" + this.getTags() + ", isOfficial=" + this.getIsOfficial() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", deletedAt=" + this.getDeletedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Playlist() {
    }

    @java.lang.SuppressWarnings("all")
    public Playlist(final Long id, final String playlistId, final String name, final String cover, final String description, final String creatorUid, final Integer songCount, final Long playCount, final Integer collectCount, final String tags, final Integer isOfficial, final Integer status, final LocalDateTime createdAt, final LocalDateTime updatedAt, final LocalDateTime deletedAt) {
        this.id = id;
        this.playlistId = playlistId;
        this.name = name;
        this.cover = cover;
        this.description = description;
        this.creatorUid = creatorUid;
        this.songCount = songCount;
        this.playCount = playCount;
        this.collectCount = collectCount;
        this.tags = tags;
        this.isOfficial = isOfficial;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }
}
