// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_play_history")
public class PlayHistory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "uid")
    private String uid;
    @Column(name = "song_id")
    private String songId;
    @Column(name = "progress")
    private Integer progress;
    @Column(name = "duration")
    private Integer duration;
    @Column(name = "quality")
    private String quality;
    @Column(name = "play_source")
    private String playSource;
    @Column(name = "source_id")
    private String sourceId;
    @Column(name = "device")
    private String device;
    @Column(name = "is_complete")
    private Integer isComplete;
    @Column(name = "played_at")
    private LocalDateTime playedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUid() {
        return this.uid;
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getProgress() {
        return this.progress;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public String getQuality() {
        return this.quality;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaySource() {
        return this.playSource;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDevice() {
        return this.device;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsComplete() {
        return this.isComplete;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getPlayedAt() {
        return this.playedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUid(final String uid) {
        this.uid = uid;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProgress(final Integer progress) {
        this.progress = progress;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuality(final String quality) {
        this.quality = quality;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaySource(final String playSource) {
        this.playSource = playSource;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDevice(final String device) {
        this.device = device;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsComplete(final Integer isComplete) {
        this.isComplete = isComplete;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayedAt(final LocalDateTime playedAt) {
        this.playedAt = playedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlayHistory)) return false;
        final PlayHistory other = (PlayHistory) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$progress = this.getProgress();
        final java.lang.Object other$progress = other.getProgress();
        if (this$progress == null ? other$progress != null : !this$progress.equals(other$progress)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$isComplete = this.getIsComplete();
        final java.lang.Object other$isComplete = other.getIsComplete();
        if (this$isComplete == null ? other$isComplete != null : !this$isComplete.equals(other$isComplete)) return false;
        final java.lang.Object this$uid = this.getUid();
        final java.lang.Object other$uid = other.getUid();
        if (this$uid == null ? other$uid != null : !this$uid.equals(other$uid)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$quality = this.getQuality();
        final java.lang.Object other$quality = other.getQuality();
        if (this$quality == null ? other$quality != null : !this$quality.equals(other$quality)) return false;
        final java.lang.Object this$playSource = this.getPlaySource();
        final java.lang.Object other$playSource = other.getPlaySource();
        if (this$playSource == null ? other$playSource != null : !this$playSource.equals(other$playSource)) return false;
        final java.lang.Object this$sourceId = this.getSourceId();
        final java.lang.Object other$sourceId = other.getSourceId();
        if (this$sourceId == null ? other$sourceId != null : !this$sourceId.equals(other$sourceId)) return false;
        final java.lang.Object this$device = this.getDevice();
        final java.lang.Object other$device = other.getDevice();
        if (this$device == null ? other$device != null : !this$device.equals(other$device)) return false;
        final java.lang.Object this$playedAt = this.getPlayedAt();
        final java.lang.Object other$playedAt = other.getPlayedAt();
        if (this$playedAt == null ? other$playedAt != null : !this$playedAt.equals(other$playedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlayHistory;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $progress = this.getProgress();
        result = result * PRIME + ($progress == null ? 43 : $progress.hashCode());
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $isComplete = this.getIsComplete();
        result = result * PRIME + ($isComplete == null ? 43 : $isComplete.hashCode());
        final java.lang.Object $uid = this.getUid();
        result = result * PRIME + ($uid == null ? 43 : $uid.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $quality = this.getQuality();
        result = result * PRIME + ($quality == null ? 43 : $quality.hashCode());
        final java.lang.Object $playSource = this.getPlaySource();
        result = result * PRIME + ($playSource == null ? 43 : $playSource.hashCode());
        final java.lang.Object $sourceId = this.getSourceId();
        result = result * PRIME + ($sourceId == null ? 43 : $sourceId.hashCode());
        final java.lang.Object $device = this.getDevice();
        result = result * PRIME + ($device == null ? 43 : $device.hashCode());
        final java.lang.Object $playedAt = this.getPlayedAt();
        result = result * PRIME + ($playedAt == null ? 43 : $playedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlayHistory(id=" + this.getId() + ", uid=" + this.getUid() + ", songId=" + this.getSongId() + ", progress=" + this.getProgress() + ", duration=" + this.getDuration() + ", quality=" + this.getQuality() + ", playSource=" + this.getPlaySource() + ", sourceId=" + this.getSourceId() + ", device=" + this.getDevice() + ", isComplete=" + this.getIsComplete() + ", playedAt=" + this.getPlayedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PlayHistory() {
    }

    @java.lang.SuppressWarnings("all")
    public PlayHistory(final Long id, final String uid, final String songId, final Integer progress, final Integer duration, final String quality, final String playSource, final String sourceId, final String device, final Integer isComplete, final LocalDateTime playedAt) {
        this.id = id;
        this.uid = uid;
        this.songId = songId;
        this.progress = progress;
        this.duration = duration;
        this.quality = quality;
        this.playSource = playSource;
        this.sourceId = sourceId;
        this.device = device;
        this.isComplete = isComplete;
        this.playedAt = playedAt;
    }
}
