// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_playlist_song")
public class PlaylistSong {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "playlist_id")
    private Long playlistId;
    @Column(name = "song_id")
    private Long songId;
    @Column(name = "sort_order")
    private Integer sortOrder;
    @Column(name = "added_at")
    private LocalDateTime addedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getAddedAt() {
        return this.addedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final Long playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final Long songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddedAt(final LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlaylistSong)) return false;
        final PlaylistSong other = (PlaylistSong) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$sortOrder = this.getSortOrder();
        final java.lang.Object other$sortOrder = other.getSortOrder();
        if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
        final java.lang.Object this$addedAt = this.getAddedAt();
        final java.lang.Object other$addedAt = other.getAddedAt();
        if (this$addedAt == null ? other$addedAt != null : !this$addedAt.equals(other$addedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlaylistSong;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $sortOrder = this.getSortOrder();
        result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
        final java.lang.Object $addedAt = this.getAddedAt();
        result = result * PRIME + ($addedAt == null ? 43 : $addedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlaylistSong(id=" + this.getId() + ", playlistId=" + this.getPlaylistId() + ", songId=" + this.getSongId() + ", sortOrder=" + this.getSortOrder() + ", addedAt=" + this.getAddedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PlaylistSong() {
    }

    @java.lang.SuppressWarnings("all")
    public PlaylistSong(final Long id, final Long playlistId, final Long songId, final Integer sortOrder, final LocalDateTime addedAt) {
        this.id = id;
        this.playlistId = playlistId;
        this.songId = songId;
        this.sortOrder = sortOrder;
        this.addedAt = addedAt;
    }
}
