// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_search_log")
public class SearchLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "uid")
    private String uid;
    @Column(name = "keyword")
    private String keyword;
    @Column(name = "result_count")
    private Integer resultCount;
    @Column(name = "search_type")
    private String searchType;
    @Column(name = "ip")
    private String ip;
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUid() {
        return this.uid;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeyword() {
        return this.keyword;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getResultCount() {
        return this.resultCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getSearchType() {
        return this.searchType;
    }

    @java.lang.SuppressWarnings("all")
    public String getIp() {
        return this.ip;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUid(final String uid) {
        this.uid = uid;
    }

    @java.lang.SuppressWarnings("all")
    public void setKeyword(final String keyword) {
        this.keyword = keyword;
    }

    @java.lang.SuppressWarnings("all")
    public void setResultCount(final Integer resultCount) {
        this.resultCount = resultCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setSearchType(final String searchType) {
        this.searchType = searchType;
    }

    @java.lang.SuppressWarnings("all")
    public void setIp(final String ip) {
        this.ip = ip;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SearchLog)) return false;
        final SearchLog other = (SearchLog) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$resultCount = this.getResultCount();
        final java.lang.Object other$resultCount = other.getResultCount();
        if (this$resultCount == null ? other$resultCount != null : !this$resultCount.equals(other$resultCount)) return false;
        final java.lang.Object this$uid = this.getUid();
        final java.lang.Object other$uid = other.getUid();
        if (this$uid == null ? other$uid != null : !this$uid.equals(other$uid)) return false;
        final java.lang.Object this$keyword = this.getKeyword();
        final java.lang.Object other$keyword = other.getKeyword();
        if (this$keyword == null ? other$keyword != null : !this$keyword.equals(other$keyword)) return false;
        final java.lang.Object this$searchType = this.getSearchType();
        final java.lang.Object other$searchType = other.getSearchType();
        if (this$searchType == null ? other$searchType != null : !this$searchType.equals(other$searchType)) return false;
        final java.lang.Object this$ip = this.getIp();
        final java.lang.Object other$ip = other.getIp();
        if (this$ip == null ? other$ip != null : !this$ip.equals(other$ip)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SearchLog;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $resultCount = this.getResultCount();
        result = result * PRIME + ($resultCount == null ? 43 : $resultCount.hashCode());
        final java.lang.Object $uid = this.getUid();
        result = result * PRIME + ($uid == null ? 43 : $uid.hashCode());
        final java.lang.Object $keyword = this.getKeyword();
        result = result * PRIME + ($keyword == null ? 43 : $keyword.hashCode());
        final java.lang.Object $searchType = this.getSearchType();
        result = result * PRIME + ($searchType == null ? 43 : $searchType.hashCode());
        final java.lang.Object $ip = this.getIp();
        result = result * PRIME + ($ip == null ? 43 : $ip.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SearchLog(id=" + this.getId() + ", uid=" + this.getUid() + ", keyword=" + this.getKeyword() + ", resultCount=" + this.getResultCount() + ", searchType=" + this.getSearchType() + ", ip=" + this.getIp() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SearchLog() {
    }

    @java.lang.SuppressWarnings("all")
    public SearchLog(final Long id, final String uid, final String keyword, final Integer resultCount, final String searchType, final String ip, final LocalDateTime createdAt) {
        this.id = id;
        this.uid = uid;
        this.keyword = keyword;
        this.resultCount = resultCount;
        this.searchType = searchType;
        this.ip = ip;
        this.createdAt = createdAt;
    }
}
