// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_song")
public class Song {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "song_id")
    private String songId;
    @Column(name = "name")
    private String name;
    @Column(name = "default_artist_id")
    private Long defaultArtistId;
    @Column(name = "album_id")
    private Long albumId;
    @Column(name = "duration")
    private Integer duration;
    @Column(name = "is_vip")
    private Integer isVip;
    @Column(name = "has_standard")
    private Integer hasStandard;
    @Column(name = "has_high")
    private Integer hasHigh;
    @Column(name = "has_lossless")
    private Integer hasLossless;
    @Column(name = "lyric_url")
    private String lyricUrl;
    @Column(name = "tlyric_url")
    private String tlyricUrl;
    @Column(name = "play_count")
    private Long playCount;
    @Column(name = "status")
    private Integer status;
    @Column(name = "source")
    private String source;
    @Column(name = "source_id")
    private String sourceId;
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDefaultArtistId() {
        return this.defaultArtistId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAlbumId() {
        return this.albumId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsVip() {
        return this.isVip;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasStandard() {
        return this.hasStandard;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasHigh() {
        return this.hasHigh;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasLossless() {
        return this.hasLossless;
    }

    @java.lang.SuppressWarnings("all")
    public String getLyricUrl() {
        return this.lyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getTlyricUrl() {
        return this.tlyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getSource() {
        return this.source;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDefaultArtistId(final Long defaultArtistId) {
        this.defaultArtistId = defaultArtistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbumId(final Long albumId) {
        this.albumId = albumId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsVip(final Integer isVip) {
        this.isVip = isVip;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasStandard(final Integer hasStandard) {
        this.hasStandard = hasStandard;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasHigh(final Integer hasHigh) {
        this.hasHigh = hasHigh;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasLossless(final Integer hasLossless) {
        this.hasLossless = hasLossless;
    }

    @java.lang.SuppressWarnings("all")
    public void setLyricUrl(final String lyricUrl) {
        this.lyricUrl = lyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setTlyricUrl(final String tlyricUrl) {
        this.tlyricUrl = tlyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setSource(final String source) {
        this.source = source;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Song)) return false;
        final Song other = (Song) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$defaultArtistId = this.getDefaultArtistId();
        final java.lang.Object other$defaultArtistId = other.getDefaultArtistId();
        if (this$defaultArtistId == null ? other$defaultArtistId != null : !this$defaultArtistId.equals(other$defaultArtistId)) return false;
        final java.lang.Object this$albumId = this.getAlbumId();
        final java.lang.Object other$albumId = other.getAlbumId();
        if (this$albumId == null ? other$albumId != null : !this$albumId.equals(other$albumId)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$isVip = this.getIsVip();
        final java.lang.Object other$isVip = other.getIsVip();
        if (this$isVip == null ? other$isVip != null : !this$isVip.equals(other$isVip)) return false;
        final java.lang.Object this$hasStandard = this.getHasStandard();
        final java.lang.Object other$hasStandard = other.getHasStandard();
        if (this$hasStandard == null ? other$hasStandard != null : !this$hasStandard.equals(other$hasStandard)) return false;
        final java.lang.Object this$hasHigh = this.getHasHigh();
        final java.lang.Object other$hasHigh = other.getHasHigh();
        if (this$hasHigh == null ? other$hasHigh != null : !this$hasHigh.equals(other$hasHigh)) return false;
        final java.lang.Object this$hasLossless = this.getHasLossless();
        final java.lang.Object other$hasLossless = other.getHasLossless();
        if (this$hasLossless == null ? other$hasLossless != null : !this$hasLossless.equals(other$hasLossless)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$lyricUrl = this.getLyricUrl();
        final java.lang.Object other$lyricUrl = other.getLyricUrl();
        if (this$lyricUrl == null ? other$lyricUrl != null : !this$lyricUrl.equals(other$lyricUrl)) return false;
        final java.lang.Object this$tlyricUrl = this.getTlyricUrl();
        final java.lang.Object other$tlyricUrl = other.getTlyricUrl();
        if (this$tlyricUrl == null ? other$tlyricUrl != null : !this$tlyricUrl.equals(other$tlyricUrl)) return false;
        final java.lang.Object this$source = this.getSource();
        final java.lang.Object other$source = other.getSource();
        if (this$source == null ? other$source != null : !this$source.equals(other$source)) return false;
        final java.lang.Object this$sourceId = this.getSourceId();
        final java.lang.Object other$sourceId = other.getSourceId();
        if (this$sourceId == null ? other$sourceId != null : !this$sourceId.equals(other$sourceId)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Song;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $defaultArtistId = this.getDefaultArtistId();
        result = result * PRIME + ($defaultArtistId == null ? 43 : $defaultArtistId.hashCode());
        final java.lang.Object $albumId = this.getAlbumId();
        result = result * PRIME + ($albumId == null ? 43 : $albumId.hashCode());
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $isVip = this.getIsVip();
        result = result * PRIME + ($isVip == null ? 43 : $isVip.hashCode());
        final java.lang.Object $hasStandard = this.getHasStandard();
        result = result * PRIME + ($hasStandard == null ? 43 : $hasStandard.hashCode());
        final java.lang.Object $hasHigh = this.getHasHigh();
        result = result * PRIME + ($hasHigh == null ? 43 : $hasHigh.hashCode());
        final java.lang.Object $hasLossless = this.getHasLossless();
        result = result * PRIME + ($hasLossless == null ? 43 : $hasLossless.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $lyricUrl = this.getLyricUrl();
        result = result * PRIME + ($lyricUrl == null ? 43 : $lyricUrl.hashCode());
        final java.lang.Object $tlyricUrl = this.getTlyricUrl();
        result = result * PRIME + ($tlyricUrl == null ? 43 : $tlyricUrl.hashCode());
        final java.lang.Object $source = this.getSource();
        result = result * PRIME + ($source == null ? 43 : $source.hashCode());
        final java.lang.Object $sourceId = this.getSourceId();
        result = result * PRIME + ($sourceId == null ? 43 : $sourceId.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Song(id=" + this.getId() + ", songId=" + this.getSongId() + ", name=" + this.getName() + ", defaultArtistId=" + this.getDefaultArtistId() + ", albumId=" + this.getAlbumId() + ", duration=" + this.getDuration() + ", isVip=" + this.getIsVip() + ", hasStandard=" + this.getHasStandard() + ", hasHigh=" + this.getHasHigh() + ", hasLossless=" + this.getHasLossless() + ", lyricUrl=" + this.getLyricUrl() + ", tlyricUrl=" + this.getTlyricUrl() + ", playCount=" + this.getPlayCount() + ", status=" + this.getStatus() + ", source=" + this.getSource() + ", sourceId=" + this.getSourceId() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Song() {
    }

    @java.lang.SuppressWarnings("all")
    public Song(final Long id, final String songId, final String name, final Long defaultArtistId, final Long albumId, final Integer duration, final Integer isVip, final Integer hasStandard, final Integer hasHigh, final Integer hasLossless, final String lyricUrl, final String tlyricUrl, final Long playCount, final Integer status, final String source, final String sourceId, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.songId = songId;
        this.name = name;
        this.defaultArtistId = defaultArtistId;
        this.albumId = albumId;
        this.duration = duration;
        this.isVip = isVip;
        this.hasStandard = hasStandard;
        this.hasHigh = hasHigh;
        this.hasLossless = hasLossless;
        this.lyricUrl = lyricUrl;
        this.tlyricUrl = tlyricUrl;
        this.playCount = playCount;
        this.status = status;
        this.source = source;
        this.sourceId = sourceId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
