// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "t_song_artist")
public class SongArtist {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "song_id")
    private Long songId;
    @Column(name = "artist_id")
    private Long artistId;
    @Column(name = "role")
    private String role;
    @Column(name = "sort_order")
    private Integer sortOrder;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getArtistId() {
        return this.artistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final Long songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtistId(final Long artistId) {
        this.artistId = artistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SongArtist)) return false;
        final SongArtist other = (SongArtist) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$artistId = this.getArtistId();
        final java.lang.Object other$artistId = other.getArtistId();
        if (this$artistId == null ? other$artistId != null : !this$artistId.equals(other$artistId)) return false;
        final java.lang.Object this$sortOrder = this.getSortOrder();
        final java.lang.Object other$sortOrder = other.getSortOrder();
        if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SongArtist;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $artistId = this.getArtistId();
        result = result * PRIME + ($artistId == null ? 43 : $artistId.hashCode());
        final java.lang.Object $sortOrder = this.getSortOrder();
        result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SongArtist(id=" + this.getId() + ", songId=" + this.getSongId() + ", artistId=" + this.getArtistId() + ", role=" + this.getRole() + ", sortOrder=" + this.getSortOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SongArtist() {
    }

    @java.lang.SuppressWarnings("all")
    public SongArtist(final Long id, final Long songId, final Long artistId, final String role, final Integer sortOrder) {
        this.id = id;
        this.songId = songId;
        this.artistId = artistId;
        this.role = role;
        this.sortOrder = sortOrder;
    }
}
