// Generated by delombok at Sat Jun 13 15:31:16 CST 2026
package com.xx.music.model.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "t_user")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "uid")
    private String uid;
    @Column(name = "phone")
    private String phone;
    @Column(name = "password")
    private String password;
    @Column(name = "nickname")
    private String nickname;
    @Column(name = "avatar")
    private String avatar;
    @Column(name = "gender")
    private Integer gender;
    @Column(name = "birthday")
    private LocalDate birthday;
    @Column(name = "signature")
    private String signature;
    @Column(name = "status")
    private Integer status;
    @Column(name = "login_fail_count")
    private Integer loginFailCount;
    @Column(name = "lock_until")
    private LocalDateTime lockUntil;
    @Column(name = "last_login_at")
    private LocalDateTime lastLoginAt;
    @Column(name = "last_login_ip")
    private String lastLoginIp;
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUid() {
        return this.uid;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getNickname() {
        return this.nickname;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getBirthday() {
        return this.birthday;
    }

    @java.lang.SuppressWarnings("all")
    public String getSignature() {
        return this.signature;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLoginFailCount() {
        return this.loginFailCount;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLockUntil() {
        return this.lockUntil;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastLoginIp() {
        return this.lastLoginIp;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getDeletedAt() {
        return this.deletedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUid(final String uid) {
        this.uid = uid;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    public void setGender(final Integer gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    public void setBirthday(final LocalDate birthday) {
        this.birthday = birthday;
    }

    @java.lang.SuppressWarnings("all")
    public void setSignature(final String signature) {
        this.signature = signature;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setLoginFailCount(final Integer loginFailCount) {
        this.loginFailCount = loginFailCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLockUntil(final LocalDateTime lockUntil) {
        this.lockUntil = lockUntil;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginAt(final LocalDateTime lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginIp(final String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeletedAt(final LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$gender = this.getGender();
        final java.lang.Object other$gender = other.getGender();
        if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$loginFailCount = this.getLoginFailCount();
        final java.lang.Object other$loginFailCount = other.getLoginFailCount();
        if (this$loginFailCount == null ? other$loginFailCount != null : !this$loginFailCount.equals(other$loginFailCount)) return false;
        final java.lang.Object this$uid = this.getUid();
        final java.lang.Object other$uid = other.getUid();
        if (this$uid == null ? other$uid != null : !this$uid.equals(other$uid)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$nickname = this.getNickname();
        final java.lang.Object other$nickname = other.getNickname();
        if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
        final java.lang.Object this$avatar = this.getAvatar();
        final java.lang.Object other$avatar = other.getAvatar();
        if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
        final java.lang.Object this$birthday = this.getBirthday();
        final java.lang.Object other$birthday = other.getBirthday();
        if (this$birthday == null ? other$birthday != null : !this$birthday.equals(other$birthday)) return false;
        final java.lang.Object this$signature = this.getSignature();
        final java.lang.Object other$signature = other.getSignature();
        if (this$signature == null ? other$signature != null : !this$signature.equals(other$signature)) return false;
        final java.lang.Object this$lockUntil = this.getLockUntil();
        final java.lang.Object other$lockUntil = other.getLockUntil();
        if (this$lockUntil == null ? other$lockUntil != null : !this$lockUntil.equals(other$lockUntil)) return false;
        final java.lang.Object this$lastLoginAt = this.getLastLoginAt();
        final java.lang.Object other$lastLoginAt = other.getLastLoginAt();
        if (this$lastLoginAt == null ? other$lastLoginAt != null : !this$lastLoginAt.equals(other$lastLoginAt)) return false;
        final java.lang.Object this$lastLoginIp = this.getLastLoginIp();
        final java.lang.Object other$lastLoginIp = other.getLastLoginIp();
        if (this$lastLoginIp == null ? other$lastLoginIp != null : !this$lastLoginIp.equals(other$lastLoginIp)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$deletedAt = this.getDeletedAt();
        final java.lang.Object other$deletedAt = other.getDeletedAt();
        if (this$deletedAt == null ? other$deletedAt != null : !this$deletedAt.equals(other$deletedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $gender = this.getGender();
        result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $loginFailCount = this.getLoginFailCount();
        result = result * PRIME + ($loginFailCount == null ? 43 : $loginFailCount.hashCode());
        final java.lang.Object $uid = this.getUid();
        result = result * PRIME + ($uid == null ? 43 : $uid.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $nickname = this.getNickname();
        result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
        final java.lang.Object $avatar = this.getAvatar();
        result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
        final java.lang.Object $birthday = this.getBirthday();
        result = result * PRIME + ($birthday == null ? 43 : $birthday.hashCode());
        final java.lang.Object $signature = this.getSignature();
        result = result * PRIME + ($signature == null ? 43 : $signature.hashCode());
        final java.lang.Object $lockUntil = this.getLockUntil();
        result = result * PRIME + ($lockUntil == null ? 43 : $lockUntil.hashCode());
        final java.lang.Object $lastLoginAt = this.getLastLoginAt();
        result = result * PRIME + ($lastLoginAt == null ? 43 : $lastLoginAt.hashCode());
        final java.lang.Object $lastLoginIp = this.getLastLoginIp();
        result = result * PRIME + ($lastLoginIp == null ? 43 : $lastLoginIp.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $deletedAt = this.getDeletedAt();
        result = result * PRIME + ($deletedAt == null ? 43 : $deletedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", uid=" + this.getUid() + ", phone=" + this.getPhone() + ", password=" + this.getPassword() + ", nickname=" + this.getNickname() + ", avatar=" + this.getAvatar() + ", gender=" + this.getGender() + ", birthday=" + this.getBirthday() + ", signature=" + this.getSignature() + ", status=" + this.getStatus() + ", loginFailCount=" + this.getLoginFailCount() + ", lockUntil=" + this.getLockUntil() + ", lastLoginAt=" + this.getLastLoginAt() + ", lastLoginIp=" + this.getLastLoginIp() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", deletedAt=" + this.getDeletedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public User() {
    }

    @java.lang.SuppressWarnings("all")
    public User(final Long id, final String uid, final String phone, final String password, final String nickname, final String avatar, final Integer gender, final LocalDate birthday, final String signature, final Integer status, final Integer loginFailCount, final LocalDateTime lockUntil, final LocalDateTime lastLoginAt, final String lastLoginIp, final LocalDateTime createdAt, final LocalDateTime updatedAt, final LocalDateTime deletedAt) {
        this.id = id;
        this.uid = uid;
        this.phone = phone;
        this.password = password;
        this.nickname = nickname;
        this.avatar = avatar;
        this.gender = gender;
        this.birthday = birthday;
        this.signature = signature;
        this.status = status;
        this.loginFailCount = loginFailCount;
        this.lockUntil = lockUntil;
        this.lastLoginAt = lastLoginAt;
        this.lastLoginIp = lastLoginIp;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }
}
