// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;
import java.util.List;

public class AdminSongVO {
    private String songId;
    private String name;
    private List<ArtistDetailVO> artists;
    private AlbumVO album;
    private Integer duration;
    private Long playCount;
    private Integer isVip;
    private Integer status;
    private String source;
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    public AdminSongVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<ArtistDetailVO> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public AlbumVO getAlbum() {
        return this.album;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsVip() {
        return this.isVip;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getSource() {
        return this.source;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final List<ArtistDetailVO> artists) {
        this.artists = artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbum(final AlbumVO album) {
        this.album = album;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsVip(final Integer isVip) {
        this.isVip = isVip;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setSource(final String source) {
        this.source = source;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminSongVO)) return false;
        final AdminSongVO other = (AdminSongVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$isVip = this.getIsVip();
        final java.lang.Object other$isVip = other.getIsVip();
        if (this$isVip == null ? other$isVip != null : !this$isVip.equals(other$isVip)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        final java.lang.Object this$album = this.getAlbum();
        final java.lang.Object other$album = other.getAlbum();
        if (this$album == null ? other$album != null : !this$album.equals(other$album)) return false;
        final java.lang.Object this$source = this.getSource();
        final java.lang.Object other$source = other.getSource();
        if (this$source == null ? other$source != null : !this$source.equals(other$source)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminSongVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $isVip = this.getIsVip();
        result = result * PRIME + ($isVip == null ? 43 : $isVip.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        final java.lang.Object $album = this.getAlbum();
        result = result * PRIME + ($album == null ? 43 : $album.hashCode());
        final java.lang.Object $source = this.getSource();
        result = result * PRIME + ($source == null ? 43 : $source.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminSongVO(songId=" + this.getSongId() + ", name=" + this.getName() + ", artists=" + this.getArtists() + ", album=" + this.getAlbum() + ", duration=" + this.getDuration() + ", playCount=" + this.getPlayCount() + ", isVip=" + this.getIsVip() + ", status=" + this.getStatus() + ", source=" + this.getSource() + ", createdAt=" + this.getCreatedAt() + ")";
    }
}
