// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import com.xx.music.common.PageResult;
import java.util.List;

public class AdminSongListVO {
    private List<AdminSongVO> list;
    private PageResult.Pagination pagination;
    private AdminSongStatsVO statistics;

    @java.lang.SuppressWarnings("all")
    public AdminSongListVO() {
    }

    @java.lang.SuppressWarnings("all")
    public List<AdminSongVO> getList() {
        return this.list;
    }

    @java.lang.SuppressWarnings("all")
    public PageResult.Pagination getPagination() {
        return this.pagination;
    }

    @java.lang.SuppressWarnings("all")
    public AdminSongStatsVO getStatistics() {
        return this.statistics;
    }

    @java.lang.SuppressWarnings("all")
    public void setList(final List<AdminSongVO> list) {
        this.list = list;
    }

    @java.lang.SuppressWarnings("all")
    public void setPagination(final PageResult.Pagination pagination) {
        this.pagination = pagination;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatistics(final AdminSongStatsVO statistics) {
        this.statistics = statistics;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminSongListVO)) return false;
        final AdminSongListVO other = (AdminSongListVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$list = this.getList();
        final java.lang.Object other$list = other.getList();
        if (this$list == null ? other$list != null : !this$list.equals(other$list)) return false;
        final java.lang.Object this$pagination = this.getPagination();
        final java.lang.Object other$pagination = other.getPagination();
        if (this$pagination == null ? other$pagination != null : !this$pagination.equals(other$pagination)) return false;
        final java.lang.Object this$statistics = this.getStatistics();
        final java.lang.Object other$statistics = other.getStatistics();
        if (this$statistics == null ? other$statistics != null : !this$statistics.equals(other$statistics)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminSongListVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $list = this.getList();
        result = result * PRIME + ($list == null ? 43 : $list.hashCode());
        final java.lang.Object $pagination = this.getPagination();
        result = result * PRIME + ($pagination == null ? 43 : $pagination.hashCode());
        final java.lang.Object $statistics = this.getStatistics();
        result = result * PRIME + ($statistics == null ? 43 : $statistics.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminSongListVO(list=" + this.getList() + ", pagination=" + this.getPagination() + ", statistics=" + this.getStatistics() + ")";
    }
}
