// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class AdminUserStatsVO {
    private long totalUsers;
    private long activeUsers;
    private long disabledUsers;
    private long todayRegistered;

    @java.lang.SuppressWarnings("all")
    public AdminUserStatsVO() {
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalUsers() {
        return this.totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getActiveUsers() {
        return this.activeUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getDisabledUsers() {
        return this.disabledUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getTodayRegistered() {
        return this.todayRegistered;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalUsers(final long totalUsers) {
        this.totalUsers = totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveUsers(final long activeUsers) {
        this.activeUsers = activeUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setDisabledUsers(final long disabledUsers) {
        this.disabledUsers = disabledUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTodayRegistered(final long todayRegistered) {
        this.todayRegistered = todayRegistered;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminUserStatsVO)) return false;
        final AdminUserStatsVO other = (AdminUserStatsVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalUsers() != other.getTotalUsers()) return false;
        if (this.getActiveUsers() != other.getActiveUsers()) return false;
        if (this.getDisabledUsers() != other.getDisabledUsers()) return false;
        if (this.getTodayRegistered() != other.getTodayRegistered()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminUserStatsVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalUsers = this.getTotalUsers();
        result = result * PRIME + (int) ($totalUsers >>> 32 ^ $totalUsers);
        final long $activeUsers = this.getActiveUsers();
        result = result * PRIME + (int) ($activeUsers >>> 32 ^ $activeUsers);
        final long $disabledUsers = this.getDisabledUsers();
        result = result * PRIME + (int) ($disabledUsers >>> 32 ^ $disabledUsers);
        final long $todayRegistered = this.getTodayRegistered();
        result = result * PRIME + (int) ($todayRegistered >>> 32 ^ $todayRegistered);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminUserStatsVO(totalUsers=" + this.getTotalUsers() + ", activeUsers=" + this.getActiveUsers() + ", disabledUsers=" + this.getDisabledUsers() + ", todayRegistered=" + this.getTodayRegistered() + ")";
    }
}
