// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;

public class AdminUserVO {
    private String uid;
    private String phone;
    private String nickname;
    private String avatar;
    private Integer gender;
    private Integer status;
    private Integer memberLevel;
    private Integer loginFailCount;
    private LocalDateTime lastLoginAt;
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    public AdminUserVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getUid() {
        return this.uid;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getNickname() {
        return this.nickname;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getMemberLevel() {
        return this.memberLevel;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLoginFailCount() {
        return this.loginFailCount;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUid(final String uid) {
        this.uid = uid;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    public void setGender(final Integer gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setMemberLevel(final Integer memberLevel) {
        this.memberLevel = memberLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setLoginFailCount(final Integer loginFailCount) {
        this.loginFailCount = loginFailCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginAt(final LocalDateTime lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminUserVO)) return false;
        final AdminUserVO other = (AdminUserVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gender = this.getGender();
        final java.lang.Object other$gender = other.getGender();
        if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$memberLevel = this.getMemberLevel();
        final java.lang.Object other$memberLevel = other.getMemberLevel();
        if (this$memberLevel == null ? other$memberLevel != null : !this$memberLevel.equals(other$memberLevel)) return false;
        final java.lang.Object this$loginFailCount = this.getLoginFailCount();
        final java.lang.Object other$loginFailCount = other.getLoginFailCount();
        if (this$loginFailCount == null ? other$loginFailCount != null : !this$loginFailCount.equals(other$loginFailCount)) return false;
        final java.lang.Object this$uid = this.getUid();
        final java.lang.Object other$uid = other.getUid();
        if (this$uid == null ? other$uid != null : !this$uid.equals(other$uid)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$nickname = this.getNickname();
        final java.lang.Object other$nickname = other.getNickname();
        if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
        final java.lang.Object this$avatar = this.getAvatar();
        final java.lang.Object other$avatar = other.getAvatar();
        if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
        final java.lang.Object this$lastLoginAt = this.getLastLoginAt();
        final java.lang.Object other$lastLoginAt = other.getLastLoginAt();
        if (this$lastLoginAt == null ? other$lastLoginAt != null : !this$lastLoginAt.equals(other$lastLoginAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminUserVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gender = this.getGender();
        result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $memberLevel = this.getMemberLevel();
        result = result * PRIME + ($memberLevel == null ? 43 : $memberLevel.hashCode());
        final java.lang.Object $loginFailCount = this.getLoginFailCount();
        result = result * PRIME + ($loginFailCount == null ? 43 : $loginFailCount.hashCode());
        final java.lang.Object $uid = this.getUid();
        result = result * PRIME + ($uid == null ? 43 : $uid.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $nickname = this.getNickname();
        result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
        final java.lang.Object $avatar = this.getAvatar();
        result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
        final java.lang.Object $lastLoginAt = this.getLastLoginAt();
        result = result * PRIME + ($lastLoginAt == null ? 43 : $lastLoginAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminUserVO(uid=" + this.getUid() + ", phone=" + this.getPhone() + ", nickname=" + this.getNickname() + ", avatar=" + this.getAvatar() + ", gender=" + this.getGender() + ", status=" + this.getStatus() + ", memberLevel=" + this.getMemberLevel() + ", loginFailCount=" + this.getLoginFailCount() + ", lastLoginAt=" + this.getLastLoginAt() + ", createdAt=" + this.getCreatedAt() + ")";
    }
}
