// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class AdminSongStatsVO {
    private long totalSongs;
    private long onlineSongs;
    private long offlineSongs;
    private long vipSongs;

    @java.lang.SuppressWarnings("all")
    public AdminSongStatsVO() {
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalSongs() {
        return this.totalSongs;
    }

    @java.lang.SuppressWarnings("all")
    public long getOnlineSongs() {
        return this.onlineSongs;
    }

    @java.lang.SuppressWarnings("all")
    public long getOfflineSongs() {
        return this.offlineSongs;
    }

    @java.lang.SuppressWarnings("all")
    public long getVipSongs() {
        return this.vipSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSongs(final long totalSongs) {
        this.totalSongs = totalSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setOnlineSongs(final long onlineSongs) {
        this.onlineSongs = onlineSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setOfflineSongs(final long offlineSongs) {
        this.offlineSongs = offlineSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setVipSongs(final long vipSongs) {
        this.vipSongs = vipSongs;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminSongStatsVO)) return false;
        final AdminSongStatsVO other = (AdminSongStatsVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalSongs() != other.getTotalSongs()) return false;
        if (this.getOnlineSongs() != other.getOnlineSongs()) return false;
        if (this.getOfflineSongs() != other.getOfflineSongs()) return false;
        if (this.getVipSongs() != other.getVipSongs()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminSongStatsVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalSongs = this.getTotalSongs();
        result = result * PRIME + (int) ($totalSongs >>> 32 ^ $totalSongs);
        final long $onlineSongs = this.getOnlineSongs();
        result = result * PRIME + (int) ($onlineSongs >>> 32 ^ $onlineSongs);
        final long $offlineSongs = this.getOfflineSongs();
        result = result * PRIME + (int) ($offlineSongs >>> 32 ^ $offlineSongs);
        final long $vipSongs = this.getVipSongs();
        result = result * PRIME + (int) ($vipSongs >>> 32 ^ $vipSongs);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminSongStatsVO(totalSongs=" + this.getTotalSongs() + ", onlineSongs=" + this.getOnlineSongs() + ", offlineSongs=" + this.getOfflineSongs() + ", vipSongs=" + this.getVipSongs() + ")";
    }
}
