// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;
import java.util.List;

public class AdminDashboardVO {
    private long totalUsers;
    private long todayNewUsers;
    private long totalSongs;
    private long activeSongs;
    private long totalPlaylists;
    private long todayPlayCount;
    private List<RecentAction> recentActions;


    public static class RecentAction {
        private String adminUsername;
        private String action;
        private String target;
        private LocalDateTime time;

        @java.lang.SuppressWarnings("all")
        public RecentAction() {
        }

        @java.lang.SuppressWarnings("all")
        public String getAdminUsername() {
            return this.adminUsername;
        }

        @java.lang.SuppressWarnings("all")
        public String getAction() {
            return this.action;
        }

        @java.lang.SuppressWarnings("all")
        public String getTarget() {
            return this.target;
        }

        @java.lang.SuppressWarnings("all")
        public LocalDateTime getTime() {
            return this.time;
        }

        @java.lang.SuppressWarnings("all")
        public void setAdminUsername(final String adminUsername) {
            this.adminUsername = adminUsername;
        }

        @java.lang.SuppressWarnings("all")
        public void setAction(final String action) {
            this.action = action;
        }

        @java.lang.SuppressWarnings("all")
        public void setTarget(final String target) {
            this.target = target;
        }

        @java.lang.SuppressWarnings("all")
        public void setTime(final LocalDateTime time) {
            this.time = time;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AdminDashboardVO.RecentAction)) return false;
            final AdminDashboardVO.RecentAction other = (AdminDashboardVO.RecentAction) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$adminUsername = this.getAdminUsername();
            final java.lang.Object other$adminUsername = other.getAdminUsername();
            if (this$adminUsername == null ? other$adminUsername != null : !this$adminUsername.equals(other$adminUsername)) return false;
            final java.lang.Object this$action = this.getAction();
            final java.lang.Object other$action = other.getAction();
            if (this$action == null ? other$action != null : !this$action.equals(other$action)) return false;
            final java.lang.Object this$target = this.getTarget();
            final java.lang.Object other$target = other.getTarget();
            if (this$target == null ? other$target != null : !this$target.equals(other$target)) return false;
            final java.lang.Object this$time = this.getTime();
            final java.lang.Object other$time = other.getTime();
            if (this$time == null ? other$time != null : !this$time.equals(other$time)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AdminDashboardVO.RecentAction;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $adminUsername = this.getAdminUsername();
            result = result * PRIME + ($adminUsername == null ? 43 : $adminUsername.hashCode());
            final java.lang.Object $action = this.getAction();
            result = result * PRIME + ($action == null ? 43 : $action.hashCode());
            final java.lang.Object $target = this.getTarget();
            result = result * PRIME + ($target == null ? 43 : $target.hashCode());
            final java.lang.Object $time = this.getTime();
            result = result * PRIME + ($time == null ? 43 : $time.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AdminDashboardVO.RecentAction(adminUsername=" + this.getAdminUsername() + ", action=" + this.getAction() + ", target=" + this.getTarget() + ", time=" + this.getTime() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public AdminDashboardVO() {
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalUsers() {
        return this.totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getTodayNewUsers() {
        return this.todayNewUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalSongs() {
        return this.totalSongs;
    }

    @java.lang.SuppressWarnings("all")
    public long getActiveSongs() {
        return this.activeSongs;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalPlaylists() {
        return this.totalPlaylists;
    }

    @java.lang.SuppressWarnings("all")
    public long getTodayPlayCount() {
        return this.todayPlayCount;
    }

    @java.lang.SuppressWarnings("all")
    public List<RecentAction> getRecentActions() {
        return this.recentActions;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalUsers(final long totalUsers) {
        this.totalUsers = totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTodayNewUsers(final long todayNewUsers) {
        this.todayNewUsers = todayNewUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSongs(final long totalSongs) {
        this.totalSongs = totalSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveSongs(final long activeSongs) {
        this.activeSongs = activeSongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPlaylists(final long totalPlaylists) {
        this.totalPlaylists = totalPlaylists;
    }

    @java.lang.SuppressWarnings("all")
    public void setTodayPlayCount(final long todayPlayCount) {
        this.todayPlayCount = todayPlayCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecentActions(final List<RecentAction> recentActions) {
        this.recentActions = recentActions;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminDashboardVO)) return false;
        final AdminDashboardVO other = (AdminDashboardVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalUsers() != other.getTotalUsers()) return false;
        if (this.getTodayNewUsers() != other.getTodayNewUsers()) return false;
        if (this.getTotalSongs() != other.getTotalSongs()) return false;
        if (this.getActiveSongs() != other.getActiveSongs()) return false;
        if (this.getTotalPlaylists() != other.getTotalPlaylists()) return false;
        if (this.getTodayPlayCount() != other.getTodayPlayCount()) return false;
        final java.lang.Object this$recentActions = this.getRecentActions();
        final java.lang.Object other$recentActions = other.getRecentActions();
        if (this$recentActions == null ? other$recentActions != null : !this$recentActions.equals(other$recentActions)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminDashboardVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalUsers = this.getTotalUsers();
        result = result * PRIME + (int) ($totalUsers >>> 32 ^ $totalUsers);
        final long $todayNewUsers = this.getTodayNewUsers();
        result = result * PRIME + (int) ($todayNewUsers >>> 32 ^ $todayNewUsers);
        final long $totalSongs = this.getTotalSongs();
        result = result * PRIME + (int) ($totalSongs >>> 32 ^ $totalSongs);
        final long $activeSongs = this.getActiveSongs();
        result = result * PRIME + (int) ($activeSongs >>> 32 ^ $activeSongs);
        final long $totalPlaylists = this.getTotalPlaylists();
        result = result * PRIME + (int) ($totalPlaylists >>> 32 ^ $totalPlaylists);
        final long $todayPlayCount = this.getTodayPlayCount();
        result = result * PRIME + (int) ($todayPlayCount >>> 32 ^ $todayPlayCount);
        final java.lang.Object $recentActions = this.getRecentActions();
        result = result * PRIME + ($recentActions == null ? 43 : $recentActions.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminDashboardVO(totalUsers=" + this.getTotalUsers() + ", todayNewUsers=" + this.getTodayNewUsers() + ", totalSongs=" + this.getTotalSongs() + ", activeSongs=" + this.getActiveSongs() + ", totalPlaylists=" + this.getTotalPlaylists() + ", todayPlayCount=" + this.getTodayPlayCount() + ", recentActions=" + this.getRecentActions() + ")";
    }
}
