// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class AlbumVO {
    private String albumId;
    private String name;
    private String cover;
    private String publishDate;

    @java.lang.SuppressWarnings("all")
    public AlbumVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAlbumId() {
        return this.albumId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbumId(final String albumId) {
        this.albumId = albumId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    public String getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(final String publishDate) {
        this.publishDate = publishDate;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AlbumVO)) return false;
        final AlbumVO other = (AlbumVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$albumId = this.getAlbumId();
        final java.lang.Object other$albumId = other.getAlbumId();
        if (this$albumId == null ? other$albumId != null : !this$albumId.equals(other$albumId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AlbumVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $albumId = this.getAlbumId();
        result = result * PRIME + ($albumId == null ? 43 : $albumId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AlbumVO(albumId=" + this.getAlbumId() + ", name=" + this.getName() + ", cover=" + this.getCover() + ")";
    }
}
