// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.util.List;

public class DailySongVO {
    private String songId;
    private String name;
    private List<ArtistVO> artists;
    private String coverUrl;
    private Integer duration;
    private String reason;

    @java.lang.SuppressWarnings("all")
    public DailySongVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<ArtistVO> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public String getCoverUrl() {
        return this.coverUrl;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final List<ArtistVO> artists) {
        this.artists = artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setCoverUrl(final String coverUrl) {
        this.coverUrl = coverUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DailySongVO)) return false;
        final DailySongVO other = (DailySongVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        final java.lang.Object this$coverUrl = this.getCoverUrl();
        final java.lang.Object other$coverUrl = other.getCoverUrl();
        if (this$coverUrl == null ? other$coverUrl != null : !this$coverUrl.equals(other$coverUrl)) return false;
        final java.lang.Object this$reason = this.getReason();
        final java.lang.Object other$reason = other.getReason();
        if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DailySongVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        final java.lang.Object $coverUrl = this.getCoverUrl();
        result = result * PRIME + ($coverUrl == null ? 43 : $coverUrl.hashCode());
        final java.lang.Object $reason = this.getReason();
        result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DailySongVO(songId=" + this.getSongId() + ", name=" + this.getName() + ", artists=" + this.getArtists() + ", coverUrl=" + this.getCoverUrl() + ", duration=" + this.getDuration() + ", reason=" + this.getReason() + ")";
    }
}
