// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.util.List;

public class HotKeywordsVO {
    private List<String> keywords;


    public static class HotKeyword {
        private String keyword;
        private int hot;

        @java.lang.SuppressWarnings("all")
        public HotKeyword() {
        }

        @java.lang.SuppressWarnings("all")
        public String getKeyword() {
            return this.keyword;
        }

        @java.lang.SuppressWarnings("all")
        public int getHot() {
            return this.hot;
        }

        @java.lang.SuppressWarnings("all")
        public void setKeyword(final String keyword) {
            this.keyword = keyword;
        }

        @java.lang.SuppressWarnings("all")
        public void setHot(final int hot) {
            this.hot = hot;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof HotKeywordsVO.HotKeyword)) return false;
            final HotKeywordsVO.HotKeyword other = (HotKeywordsVO.HotKeyword) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getHot() != other.getHot()) return false;
            final java.lang.Object this$keyword = this.getKeyword();
            final java.lang.Object other$keyword = other.getKeyword();
            if (this$keyword == null ? other$keyword != null : !this$keyword.equals(other$keyword)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof HotKeywordsVO.HotKeyword;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getHot();
            final java.lang.Object $keyword = this.getKeyword();
            result = result * PRIME + ($keyword == null ? 43 : $keyword.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "HotKeywordsVO.HotKeyword(keyword=" + this.getKeyword() + ", hot=" + this.getHot() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public HotKeywordsVO() {
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getKeywords() {
        return this.keywords;
    }

    public void setKeywords(final List<String> keywords) {
        this.keywords = keywords;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof HotKeywordsVO)) return false;
        final HotKeywordsVO other = (HotKeywordsVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$keywords = this.getKeywords();
        final java.lang.Object other$keywords = other.getKeywords();
        if (this$keywords == null ? other$keywords != null : !this$keywords.equals(other$keywords)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof HotKeywordsVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $keywords = this.getKeywords();
        result = result * PRIME + ($keywords == null ? 43 : $keywords.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "HotKeywordsVO(keywords=" + this.getKeywords() + ")";
    }
}
