// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.util.List;

public class HotSongVO {
    private Integer rank;
    private String songId;
    private String name;
    private List<ArtistVO> artists;
    private Long playCount;
    private Integer duration;
    private Integer isVip;
    private List<String> artistNames;
    private List<String> artistIds;

    @java.lang.SuppressWarnings("all")
    public HotSongVO() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getRank() {
        return this.rank;
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<ArtistVO> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setRank(final Integer rank) {
        this.rank = rank;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final List<ArtistVO> artists) {
        this.artists = artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    public Integer getIsVip() {
        return this.isVip;
    }

    public void setIsVip(final Integer isVip) {
        this.isVip = isVip;
    }

    public List<String> getArtistNames() {
        return this.artistNames;
    }

    public void setArtistNames(final List<String> artistNames) {
        this.artistNames = artistNames;
    }

    public List<String> getArtistIds() {
        return this.artistIds;
    }

    public void setArtistIds(final List<String> artistIds) {
        this.artistIds = artistIds;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof HotSongVO)) return false;
        final HotSongVO other = (HotSongVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$rank = this.getRank();
        final java.lang.Object other$rank = other.getRank();
        if (this$rank == null ? other$rank != null : !this$rank.equals(other$rank)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof HotSongVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $rank = this.getRank();
        result = result * PRIME + ($rank == null ? 43 : $rank.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "HotSongVO(rank=" + this.getRank() + ", songId=" + this.getSongId() + ", name=" + this.getName() + ", artists=" + this.getArtists() + ", playCount=" + this.getPlayCount() + ")";
    }
}
