// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class LyricVO {
    private String songId;
    private String lyric;
    private String tlyric;

    @java.lang.SuppressWarnings("all")
    public LyricVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getLyric() {
        return this.lyric;
    }

    @java.lang.SuppressWarnings("all")
    public String getTlyric() {
        return this.tlyric;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLyric(final String lyric) {
        this.lyric = lyric;
    }

    @java.lang.SuppressWarnings("all")
    public void setTlyric(final String tlyric) {
        this.tlyric = tlyric;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LyricVO)) return false;
        final LyricVO other = (LyricVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$lyric = this.getLyric();
        final java.lang.Object other$lyric = other.getLyric();
        if (this$lyric == null ? other$lyric != null : !this$lyric.equals(other$lyric)) return false;
        final java.lang.Object this$tlyric = this.getTlyric();
        final java.lang.Object other$tlyric = other.getTlyric();
        if (this$tlyric == null ? other$tlyric != null : !this$tlyric.equals(other$tlyric)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LyricVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $lyric = this.getLyric();
        result = result * PRIME + ($lyric == null ? 43 : $lyric.hashCode());
        final java.lang.Object $tlyric = this.getTlyric();
        result = result * PRIME + ($tlyric == null ? 43 : $tlyric.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LyricVO(songId=" + this.getSongId() + ", lyric=" + this.getLyric() + ", tlyric=" + this.getTlyric() + ")";
    }
}
