// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.util.List;

public class PersonalizedVO {
    private List<DailySongVO> dailySongs;
    private List<RecommendPlaylistVO> recommendPlaylists;
    private List<SongVO> songs;

    @java.lang.SuppressWarnings("all")
    public PersonalizedVO() {
    }

    @java.lang.SuppressWarnings("all")
    public List<DailySongVO> getDailySongs() {
        return this.dailySongs;
    }

    @java.lang.SuppressWarnings("all")
    public List<RecommendPlaylistVO> getRecommendPlaylists() {
        return this.recommendPlaylists;
    }

    @java.lang.SuppressWarnings("all")
    public void setDailySongs(final List<DailySongVO> dailySongs) {
        this.dailySongs = dailySongs;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecommendPlaylists(final List<RecommendPlaylistVO> recommendPlaylists) {
        this.recommendPlaylists = recommendPlaylists;
    }

    public List<SongVO> getSongs() {
        return this.songs;
    }

    public void setSongs(final List<SongVO> songs) {
        this.songs = songs;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PersonalizedVO)) return false;
        final PersonalizedVO other = (PersonalizedVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$dailySongs = this.getDailySongs();
        final java.lang.Object other$dailySongs = other.getDailySongs();
        if (this$dailySongs == null ? other$dailySongs != null : !this$dailySongs.equals(other$dailySongs)) return false;
        final java.lang.Object this$recommendPlaylists = this.getRecommendPlaylists();
        final java.lang.Object other$recommendPlaylists = other.getRecommendPlaylists();
        if (this$recommendPlaylists == null ? other$recommendPlaylists != null : !this$recommendPlaylists.equals(other$recommendPlaylists)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PersonalizedVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $dailySongs = this.getDailySongs();
        result = result * PRIME + ($dailySongs == null ? 43 : $dailySongs.hashCode());
        final java.lang.Object $recommendPlaylists = this.getRecommendPlaylists();
        result = result * PRIME + ($recommendPlaylists == null ? 43 : $recommendPlaylists.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PersonalizedVO(dailySongs=" + this.getDailySongs() + ", recommendPlaylists=" + this.getRecommendPlaylists() + ")";
    }
}
