// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;
import java.util.List;

public class PlaylistDetailVO {
    private String playlistId;
    private String name;
    private String cover;
    private String description;
    private String creatorUid;
    private String creatorNickname;
    private Integer songCount;
    private Long playCount;
    private Integer collectCount;
    private String tags;
    private Integer isOfficial;
    private List<SongVO> songs;
    private long total;
    private int page;
    private int size;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public PlaylistDetailVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getCreatorUid() {
        return this.creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public String getCreatorNickname() {
        return this.creatorNickname;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCollectCount() {
        return this.collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsOfficial() {
        return this.isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public List<SongVO> getSongs() {
        return this.songs;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotal() {
        return this.total;
    }

    @java.lang.SuppressWarnings("all")
    public int getPage() {
        return this.page;
    }

    @java.lang.SuppressWarnings("all")
    public int getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final String playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatorUid(final String creatorUid) {
        this.creatorUid = creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatorNickname(final String creatorNickname) {
        this.creatorNickname = creatorNickname;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectCount(final Integer collectCount) {
        this.collectCount = collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setTags(final String tags) {
        this.tags = tags;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsOfficial(final Integer isOfficial) {
        this.isOfficial = isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongs(final List<SongVO> songs) {
        this.songs = songs;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotal(final long total) {
        this.total = total;
    }

    @java.lang.SuppressWarnings("all")
    public void setPage(final int page) {
        this.page = page;
    }

    @java.lang.SuppressWarnings("all")
    public void setSize(final int size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlaylistDetailVO)) return false;
        final PlaylistDetailVO other = (PlaylistDetailVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$collectCount = this.getCollectCount();
        final java.lang.Object other$collectCount = other.getCollectCount();
        if (this$collectCount == null ? other$collectCount != null : !this$collectCount.equals(other$collectCount)) return false;
        final java.lang.Object this$isOfficial = this.getIsOfficial();
        final java.lang.Object other$isOfficial = other.getIsOfficial();
        if (this$isOfficial == null ? other$isOfficial != null : !this$isOfficial.equals(other$isOfficial)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$creatorUid = this.getCreatorUid();
        final java.lang.Object other$creatorUid = other.getCreatorUid();
        if (this$creatorUid == null ? other$creatorUid != null : !this$creatorUid.equals(other$creatorUid)) return false;
        final java.lang.Object this$creatorNickname = this.getCreatorNickname();
        final java.lang.Object other$creatorNickname = other.getCreatorNickname();
        if (this$creatorNickname == null ? other$creatorNickname != null : !this$creatorNickname.equals(other$creatorNickname)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$songs = this.getSongs();
        final java.lang.Object other$songs = other.getSongs();
        if (this$songs == null ? other$songs != null : !this$songs.equals(other$songs)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlaylistDetailVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $collectCount = this.getCollectCount();
        result = result * PRIME + ($collectCount == null ? 43 : $collectCount.hashCode());
        final java.lang.Object $isOfficial = this.getIsOfficial();
        result = result * PRIME + ($isOfficial == null ? 43 : $isOfficial.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $creatorUid = this.getCreatorUid();
        result = result * PRIME + ($creatorUid == null ? 43 : $creatorUid.hashCode());
        final java.lang.Object $creatorNickname = this.getCreatorNickname();
        result = result * PRIME + ($creatorNickname == null ? 43 : $creatorNickname.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $songs = this.getSongs();
        result = result * PRIME + ($songs == null ? 43 : $songs.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlaylistDetailVO(playlistId=" + this.getPlaylistId() + ", name=" + this.getName() + ", cover=" + this.getCover() + ", description=" + this.getDescription() + ", creatorUid=" + this.getCreatorUid() + ", creatorNickname=" + this.getCreatorNickname() + ", songCount=" + this.getSongCount() + ", playCount=" + this.getPlayCount() + ", collectCount=" + this.getCollectCount() + ", tags=" + this.getTags() + ", isOfficial=" + this.getIsOfficial() + ", songs=" + this.getSongs() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }
}
