// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;

public class PlaylistVO {
    private String playlistId;
    private String name;
    private String description;
    private String cover;
    private String creatorUid;
    private Integer songCount;
    private Long playCount;
    private Integer collectCount;
    private String tags;
    private Integer isOfficial;
    private Boolean isPublic;
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    public PlaylistVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCreatorUid() {
        return this.creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCollectCount() {
        return this.collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsOfficial() {
        return this.isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsPublic() {
        return this.isPublic;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final String playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatorUid(final String creatorUid) {
        this.creatorUid = creatorUid;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectCount(final Integer collectCount) {
        this.collectCount = collectCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setTags(final String tags) {
        this.tags = tags;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsOfficial(final Integer isOfficial) {
        this.isOfficial = isOfficial;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsPublic(final Boolean isPublic) {
        this.isPublic = isPublic;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlaylistVO)) return false;
        final PlaylistVO other = (PlaylistVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$isPublic = this.getIsPublic();
        final java.lang.Object other$isPublic = other.getIsPublic();
        if (this$isPublic == null ? other$isPublic != null : !this$isPublic.equals(other$isPublic)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlaylistVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $isPublic = this.getIsPublic();
        result = result * PRIME + ($isPublic == null ? 43 : $isPublic.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlaylistVO(playlistId=" + this.getPlaylistId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", cover=" + this.getCover() + ", songCount=" + this.getSongCount() + ", isPublic=" + this.getIsPublic() + ", createdAt=" + this.getCreatedAt() + ")";
    }
}
