// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class PlaylistSongResultVO {
    private String playlistId;
    private Integer songCount;
    private Integer addedCount;
    private int added;
    private java.util.List<String> duplicated;
    private int total;

    @java.lang.SuppressWarnings("all")
    public PlaylistSongResultVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getAddedCount() {
        return this.addedCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final String playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddedCount(final Integer addedCount) {
        this.addedCount = addedCount;
    }

    @java.lang.SuppressWarnings("all")
    public int getAdded() {
        return this.added;
    }

    @java.lang.SuppressWarnings("all")
    public void setAdded(final int added) {
        this.added = added;
    }

    @java.lang.SuppressWarnings("all")
    public java.util.List<String> getDuplicated() {
        return this.duplicated;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuplicated(final java.util.List<String> duplicated) {
        this.duplicated = duplicated;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotal() {
        return this.total;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotal(final int total) {
        this.total = total;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlaylistSongResultVO)) return false;
        final PlaylistSongResultVO other = (PlaylistSongResultVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$addedCount = this.getAddedCount();
        final java.lang.Object other$addedCount = other.getAddedCount();
        if (this$addedCount == null ? other$addedCount != null : !this$addedCount.equals(other$addedCount)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlaylistSongResultVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $addedCount = this.getAddedCount();
        result = result * PRIME + ($addedCount == null ? 43 : $addedCount.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlaylistSongResultVO(playlistId=" + this.getPlaylistId() + ", songCount=" + this.getSongCount() + ", addedCount=" + this.getAddedCount() + ")";
    }
}
