// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class RecommendPlaylistVO {
    private String playlistId;
    private String name;
    private String cover;
    private Integer songCount;

    @java.lang.SuppressWarnings("all")
    public RecommendPlaylistVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaylistId() {
        return this.playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCover() {
        return this.cover;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSongCount() {
        return this.songCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylistId(final String playlistId) {
        this.playlistId = playlistId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCover(final String cover) {
        this.cover = cover;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongCount(final Integer songCount) {
        this.songCount = songCount;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RecommendPlaylistVO)) return false;
        final RecommendPlaylistVO other = (RecommendPlaylistVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songCount = this.getSongCount();
        final java.lang.Object other$songCount = other.getSongCount();
        if (this$songCount == null ? other$songCount != null : !this$songCount.equals(other$songCount)) return false;
        final java.lang.Object this$playlistId = this.getPlaylistId();
        final java.lang.Object other$playlistId = other.getPlaylistId();
        if (this$playlistId == null ? other$playlistId != null : !this$playlistId.equals(other$playlistId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$cover = this.getCover();
        final java.lang.Object other$cover = other.getCover();
        if (this$cover == null ? other$cover != null : !this$cover.equals(other$cover)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RecommendPlaylistVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songCount = this.getSongCount();
        result = result * PRIME + ($songCount == null ? 43 : $songCount.hashCode());
        final java.lang.Object $playlistId = this.getPlaylistId();
        result = result * PRIME + ($playlistId == null ? 43 : $playlistId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $cover = this.getCover();
        result = result * PRIME + ($cover == null ? 43 : $cover.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RecommendPlaylistVO(playlistId=" + this.getPlaylistId() + ", name=" + this.getName() + ", cover=" + this.getCover() + ", songCount=" + this.getSongCount() + ")";
    }
}
