// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import com.xx.music.common.PageResult;
import java.util.List;

public class SearchResultVO {
    private String keyword;
    private String type;
    private PageResult<SongVO> songs;
    private PageResult<SongVO> playlists;
    private PageResult<?> artists;
    private List<PlaylistVO> playlistList;
    private List<ArtistVO> artistList;
    private PageResult.Pagination pagination;

    @java.lang.SuppressWarnings("all")
    public SearchResultVO() {
    }

    public String getKeyword() {
        return this.keyword;
    }

    public void setKeyword(final String keyword) {
        this.keyword = keyword;
    }

    public String getType() {
        return this.type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public PageResult<SongVO> getSongs() {
        return this.songs;
    }

    @java.lang.SuppressWarnings("all")
    public PageResult<SongVO> getPlaylists() {
        return this.playlists;
    }

    @java.lang.SuppressWarnings("all")
    public PageResult<?> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public PageResult.Pagination getPagination() {
        return this.pagination;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongs(final PageResult<SongVO> songs) {
        this.songs = songs;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaylists(final PageResult<SongVO> playlists) {
        this.playlists = playlists;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final PageResult<?> artists) {
        this.artists = artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setPagination(final PageResult.Pagination pagination) {
        this.pagination = pagination;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SearchResultVO)) return false;
        final SearchResultVO other = (SearchResultVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$songs = this.getSongs();
        final java.lang.Object other$songs = other.getSongs();
        if (this$songs == null ? other$songs != null : !this$songs.equals(other$songs)) return false;
        final java.lang.Object this$playlists = this.getPlaylists();
        final java.lang.Object other$playlists = other.getPlaylists();
        if (this$playlists == null ? other$playlists != null : !this$playlists.equals(other$playlists)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        final java.lang.Object this$pagination = this.getPagination();
        final java.lang.Object other$pagination = other.getPagination();
        if (this$pagination == null ? other$pagination != null : !this$pagination.equals(other$pagination)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SearchResultVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $songs = this.getSongs();
        result = result * PRIME + ($songs == null ? 43 : $songs.hashCode());
        final java.lang.Object $playlists = this.getPlaylists();
        result = result * PRIME + ($playlists == null ? 43 : $playlists.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        final java.lang.Object $pagination = this.getPagination();
        result = result * PRIME + ($pagination == null ? 43 : $pagination.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SearchResultVO(songs=" + this.getSongs() + ", playlists=" + this.getPlaylists() + ", artists=" + this.getArtists() + ", pagination=" + this.getPagination() + ")";
    }
}
