// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;
import java.util.List;

public class SongVO {
    private String songId;
    private String name;
    private List<ArtistVO> artists;
    private AlbumVO album;
    private Integer duration;
    private String coverUrl;
    private Long playCount;
    private Integer isVip;
    private LocalDateTime favoritedAt;
    private LocalDateTime addedAt;
    private List<String> artistNames;
    private List<String> artistIds;
    private Integer status;

    @java.lang.SuppressWarnings("all")
    public SongVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<ArtistVO> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public AlbumVO getAlbum() {
        return this.album;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public String getCoverUrl() {
        return this.coverUrl;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsVip() {
        return this.isVip;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getFavoritedAt() {
        return this.favoritedAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getAddedAt() {
        return this.addedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final List<ArtistVO> artists) {
        this.artists = artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbum(final AlbumVO album) {
        this.album = album;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setCoverUrl(final String coverUrl) {
        this.coverUrl = coverUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsVip(final Integer isVip) {
        this.isVip = isVip;
    }

    @java.lang.SuppressWarnings("all")
    public void setFavoritedAt(final LocalDateTime favoritedAt) {
        this.favoritedAt = favoritedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddedAt(final LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    public List<String> getArtistNames() {
        return this.artistNames;
    }

    public void setArtistNames(final List<String> artistNames) {
        this.artistNames = artistNames;
    }

    public List<String> getArtistIds() {
        return this.artistIds;
    }

    public void setArtistIds(final List<String> artistIds) {
        this.artistIds = artistIds;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SongVO)) return false;
        final SongVO other = (SongVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$isVip = this.getIsVip();
        final java.lang.Object other$isVip = other.getIsVip();
        if (this$isVip == null ? other$isVip != null : !this$isVip.equals(other$isVip)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        final java.lang.Object this$album = this.getAlbum();
        final java.lang.Object other$album = other.getAlbum();
        if (this$album == null ? other$album != null : !this$album.equals(other$album)) return false;
        final java.lang.Object this$coverUrl = this.getCoverUrl();
        final java.lang.Object other$coverUrl = other.getCoverUrl();
        if (this$coverUrl == null ? other$coverUrl != null : !this$coverUrl.equals(other$coverUrl)) return false;
        final java.lang.Object this$favoritedAt = this.getFavoritedAt();
        final java.lang.Object other$favoritedAt = other.getFavoritedAt();
        if (this$favoritedAt == null ? other$favoritedAt != null : !this$favoritedAt.equals(other$favoritedAt)) return false;
        final java.lang.Object this$addedAt = this.getAddedAt();
        final java.lang.Object other$addedAt = other.getAddedAt();
        if (this$addedAt == null ? other$addedAt != null : !this$addedAt.equals(other$addedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SongVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $isVip = this.getIsVip();
        result = result * PRIME + ($isVip == null ? 43 : $isVip.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        final java.lang.Object $album = this.getAlbum();
        result = result * PRIME + ($album == null ? 43 : $album.hashCode());
        final java.lang.Object $coverUrl = this.getCoverUrl();
        result = result * PRIME + ($coverUrl == null ? 43 : $coverUrl.hashCode());
        final java.lang.Object $favoritedAt = this.getFavoritedAt();
        result = result * PRIME + ($favoritedAt == null ? 43 : $favoritedAt.hashCode());
        final java.lang.Object $addedAt = this.getAddedAt();
        result = result * PRIME + ($addedAt == null ? 43 : $addedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SongVO(songId=" + this.getSongId() + ", name=" + this.getName() + ", artists=" + this.getArtists() + ", album=" + this.getAlbum() + ", duration=" + this.getDuration() + ", coverUrl=" + this.getCoverUrl() + ", playCount=" + this.getPlayCount() + ", isVip=" + this.getIsVip() + ", favoritedAt=" + this.getFavoritedAt() + ", addedAt=" + this.getAddedAt() + ")";
    }
}
