// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

import java.time.LocalDateTime;
import java.util.List;

public class SongDetailVO {
    private String songId;
    private String name;
    private List<ArtistDetailVO> artists;
    private AlbumVO album;
    private Integer duration;
    private Integer isVip;
    private Integer hasStandard;
    private Integer hasHigh;
    private Integer hasLossless;
    private Long playCount;
    private String lyricUrl;
    private String tlyricUrl;
    private String source;
    private String sourceId;
    private Integer status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public SongDetailVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<ArtistDetailVO> getArtists() {
        return this.artists;
    }

    @java.lang.SuppressWarnings("all")
    public AlbumVO getAlbum() {
        return this.album;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsVip() {
        return this.isVip;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasStandard() {
        return this.hasStandard;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasHigh() {
        return this.hasHigh;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getHasLossless() {
        return this.hasLossless;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlayCount() {
        return this.playCount;
    }

    @java.lang.SuppressWarnings("all")
    public String getLyricUrl() {
        return this.lyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getTlyricUrl() {
        return this.tlyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getSource() {
        return this.source;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtists(final List<ArtistVO> artists) {
        this.artists = (List<ArtistDetailVO>)(List<?>) artists;
    }

    @java.lang.SuppressWarnings("all")
    public void setAlbum(final AlbumVO album) {
        this.album = album;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsVip(final Integer isVip) {
        this.isVip = isVip;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasStandard(final Integer hasStandard) {
        this.hasStandard = hasStandard;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasHigh(final Integer hasHigh) {
        this.hasHigh = hasHigh;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasLossless(final Integer hasLossless) {
        this.hasLossless = hasLossless;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlayCount(final Long playCount) {
        this.playCount = playCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLyricUrl(final String lyricUrl) {
        this.lyricUrl = lyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setTlyricUrl(final String tlyricUrl) {
        this.tlyricUrl = tlyricUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setSource(final String source) {
        this.source = source;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceId() {
        return this.sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSourceId(final String sourceId) {
        this.sourceId = sourceId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SongDetailVO)) return false;
        final SongDetailVO other = (SongDetailVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$isVip = this.getIsVip();
        final java.lang.Object other$isVip = other.getIsVip();
        if (this$isVip == null ? other$isVip != null : !this$isVip.equals(other$isVip)) return false;
        final java.lang.Object this$hasStandard = this.getHasStandard();
        final java.lang.Object other$hasStandard = other.getHasStandard();
        if (this$hasStandard == null ? other$hasStandard != null : !this$hasStandard.equals(other$hasStandard)) return false;
        final java.lang.Object this$hasHigh = this.getHasHigh();
        final java.lang.Object other$hasHigh = other.getHasHigh();
        if (this$hasHigh == null ? other$hasHigh != null : !this$hasHigh.equals(other$hasHigh)) return false;
        final java.lang.Object this$hasLossless = this.getHasLossless();
        final java.lang.Object other$hasLossless = other.getHasLossless();
        if (this$hasLossless == null ? other$hasLossless != null : !this$hasLossless.equals(other$hasLossless)) return false;
        final java.lang.Object this$playCount = this.getPlayCount();
        final java.lang.Object other$playCount = other.getPlayCount();
        if (this$playCount == null ? other$playCount != null : !this$playCount.equals(other$playCount)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$artists = this.getArtists();
        final java.lang.Object other$artists = other.getArtists();
        if (this$artists == null ? other$artists != null : !this$artists.equals(other$artists)) return false;
        final java.lang.Object this$album = this.getAlbum();
        final java.lang.Object other$album = other.getAlbum();
        if (this$album == null ? other$album != null : !this$album.equals(other$album)) return false;
        final java.lang.Object this$lyricUrl = this.getLyricUrl();
        final java.lang.Object other$lyricUrl = other.getLyricUrl();
        if (this$lyricUrl == null ? other$lyricUrl != null : !this$lyricUrl.equals(other$lyricUrl)) return false;
        final java.lang.Object this$tlyricUrl = this.getTlyricUrl();
        final java.lang.Object other$tlyricUrl = other.getTlyricUrl();
        if (this$tlyricUrl == null ? other$tlyricUrl != null : !this$tlyricUrl.equals(other$tlyricUrl)) return false;
        final java.lang.Object this$source = this.getSource();
        final java.lang.Object other$source = other.getSource();
        if (this$source == null ? other$source != null : !this$source.equals(other$source)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SongDetailVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $isVip = this.getIsVip();
        result = result * PRIME + ($isVip == null ? 43 : $isVip.hashCode());
        final java.lang.Object $hasStandard = this.getHasStandard();
        result = result * PRIME + ($hasStandard == null ? 43 : $hasStandard.hashCode());
        final java.lang.Object $hasHigh = this.getHasHigh();
        result = result * PRIME + ($hasHigh == null ? 43 : $hasHigh.hashCode());
        final java.lang.Object $hasLossless = this.getHasLossless();
        result = result * PRIME + ($hasLossless == null ? 43 : $hasLossless.hashCode());
        final java.lang.Object $playCount = this.getPlayCount();
        result = result * PRIME + ($playCount == null ? 43 : $playCount.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $artists = this.getArtists();
        result = result * PRIME + ($artists == null ? 43 : $artists.hashCode());
        final java.lang.Object $album = this.getAlbum();
        result = result * PRIME + ($album == null ? 43 : $album.hashCode());
        final java.lang.Object $lyricUrl = this.getLyricUrl();
        result = result * PRIME + ($lyricUrl == null ? 43 : $lyricUrl.hashCode());
        final java.lang.Object $tlyricUrl = this.getTlyricUrl();
        result = result * PRIME + ($tlyricUrl == null ? 43 : $tlyricUrl.hashCode());
        final java.lang.Object $source = this.getSource();
        result = result * PRIME + ($source == null ? 43 : $source.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SongDetailVO(songId=" + this.getSongId() + ", name=" + this.getName() + ", artists=" + this.getArtists() + ", album=" + this.getAlbum() + ", duration=" + this.getDuration() + ", isVip=" + this.getIsVip() + ", hasStandard=" + this.getHasStandard() + ", hasHigh=" + this.getHasHigh() + ", hasLossless=" + this.getHasLossless() + ", playCount=" + this.getPlayCount() + ", lyricUrl=" + this.getLyricUrl() + ", tlyricUrl=" + this.getTlyricUrl() + ", source=" + this.getSource() + ")";
    }
}
