// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class StreamVO {
    private String songId;
    private String url;
    private String quality;
    private Integer duration;
    private String type;
    private Long size;

    @java.lang.SuppressWarnings("all")
    public StreamVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSongId() {
        return this.songId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public String getQuality() {
        return this.quality;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setSongId(final String songId) {
        this.songId = songId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuality(final String quality) {
        this.quality = quality;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    public String getType() {
        return this.type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public Long getSize() {
        return this.size;
    }

    public void setSize(final Long size) {
        this.size = size;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StreamVO)) return false;
        final StreamVO other = (StreamVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$songId = this.getSongId();
        final java.lang.Object other$songId = other.getSongId();
        if (this$songId == null ? other$songId != null : !this$songId.equals(other$songId)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$quality = this.getQuality();
        final java.lang.Object other$quality = other.getQuality();
        if (this$quality == null ? other$quality != null : !this$quality.equals(other$quality)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StreamVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $songId = this.getSongId();
        result = result * PRIME + ($songId == null ? 43 : $songId.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $quality = this.getQuality();
        result = result * PRIME + ($quality == null ? 43 : $quality.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "StreamVO(songId=" + this.getSongId() + ", url=" + this.getUrl() + ", quality=" + this.getQuality() + ", duration=" + this.getDuration() + ")";
    }
}
