// Generated by delombok at Sat Jun 13 15:31:52 CST 2026
package com.xx.music.model.vo;

public class TokenVO {
    private String accessToken;
    private Long expiresIn;
    private String refreshToken;

    @java.lang.SuppressWarnings("all")
    public TokenVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAccessToken() {
        return this.accessToken;
    }

    @java.lang.SuppressWarnings("all")
    public Long getExpiresIn() {
        return this.expiresIn;
    }

    @java.lang.SuppressWarnings("all")
    public void setAccessToken(final String accessToken) {
        this.accessToken = accessToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiresIn(final Long expiresIn) {
        this.expiresIn = expiresIn;
    }

    public String getRefreshToken() {
        return this.refreshToken;
    }

    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TokenVO)) return false;
        final TokenVO other = (TokenVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$expiresIn = this.getExpiresIn();
        final java.lang.Object other$expiresIn = other.getExpiresIn();
        if (this$expiresIn == null ? other$expiresIn != null : !this$expiresIn.equals(other$expiresIn)) return false;
        final java.lang.Object this$accessToken = this.getAccessToken();
        final java.lang.Object other$accessToken = other.getAccessToken();
        if (this$accessToken == null ? other$accessToken != null : !this$accessToken.equals(other$accessToken)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TokenVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $expiresIn = this.getExpiresIn();
        result = result * PRIME + ($expiresIn == null ? 43 : $expiresIn.hashCode());
        final java.lang.Object $accessToken = this.getAccessToken();
        result = result * PRIME + ($accessToken == null ? 43 : $accessToken.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TokenVO(accessToken=" + this.getAccessToken() + ", expiresIn=" + this.getExpiresIn() + ")";
    }
}
